
blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/ngageoint/ogc-api-features-json-java/discussions
    about: Questions, Feature Requests, Feedback, Conversations
